name: Release

on:
  push:
    branches: [main, beta]

jobs:
  release:
    name: Release

    steps:
    - name: Install dependencies
      run: yarn
    - name: Install semantic-release extra plugins
      run: yarn add --save-dev @semantic-release/changelog @semantic-release/git      
    - name: Lint
      run: yarn run lint-fix
    - name: Test
      run: yarn run test:unit --if-present
    - name: Build
      run: yarn run build      
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release